# These are supported funding model platforms

github: dhimasardinata
ko_fi: dhimasardinata
# open_collective: caxe

# Web3 Wallet Addresses (displayed in README)
# EVM (Ethereum/Polygon/BSC): 0x7e1a1a8c46817f297be14c14b587a0fa4b9e484b
# Solana: Bek24ZEPWHUJeTHQmDHtC7uHaHiH7TX8FmfYqtQu3Tt
# Bitcoin: bc1q4rm4e007u0f44vje694f422dy423dfc2caqz9z
